### ISSUE TITLE
Please update your readme page schematic reference

### ISSUE THREAD

**Issue by nlroth** [qrp73/NanoVNA-Q#10]
Please ensure that your schematic reference refers to hugen's latest version since you and most everyone else are using that. Your schematic link in the readme is for edy555's original - the TCXO and battery circuits are different.

There is no issue with having only the one, but please ensure your readers know where is comes from.

Thanks

**Comment by qrp73** [comment]
https://github.com/qrp73/NanoVNA-Q/commit/38ff7ef69abfcef4098a5025c128624215802bee
https://github.com/qrp73/NanoVNA-Q/commit/095682802fa685acde7c67aa712e6b86e16d1275
