### ISSUE TITLE
Glitch at 7.5MHz

### ISSUE THREAD

**Issue by owenduffy** [qrp73/NanoVNA-Q#13]
I have been drilling down on a persistent glitch measuring an inductor with relatively high impedance.

If I understand the system properly, I have obtained raw output by turning off "correction" in the menu.

The glitch is apparent sweeping an OC and SC cal part, and it is consistently around 7.5MHz no matter what sweep range is chosen.

![Screenshot-191108060508](https://user-images.githubusercontent.com/4297310/68419138-c27bed80-01ed-11ea-980f-72123025f3fe.png)

![Screenshot-191108060455](https://user-images.githubusercontent.com/4297310/68419140-c445b100-01ed-11ea-86ac-a758e4d9f188.png)

These are raw sweeps of an OC cal part.

The |s11| plot shows a spike and a small step change in the response where I would expect a smooth underlying line.

Owen

**Comment by qrp73** [comment]
this is hardware issue, may be related with shielding. 
Could you provide photo of your hardware (with removed back cover)?

I can suggest to clean PCB from flux with alcohol (95% Ethanol or Isopropyl). Also try to experiment with removed shield.

**Comment by owenduffy** [comment]
It seems to be a nanovna-H v3.3... but when you buy from China, no telling what you get.

![nanovnah04](https://user-images.githubusercontent.com/4297310/68447650-c848f180-0234-11ea-8e5e-00db53acbe9b.jpg)

Are you suggesting a hardware fault, or a hardware design issue (like leakage from clocks, communication, hash from MCU or codec)?

I have done nothing to the board, evaluating it 'out of the box'. The board is quite clean as Chinese stuff goes, and the soldering looks fairly good to the naked eye. The shields appear ok, but I will inspect the bonding to the PCB tracks. I have seen some tacked at the corners only, and I could seen that as less effective.

Yes, I have seen reports these may work better without the shields... raises questions doesn't it... it is counter intuitive if the shields are properly effective?

Remember this glitch is observed at around 7.5MHz... it is almost DC from a layout perspective.

![Screenshot-191108144250](https://user-images.githubusercontent.com/4297310/68447988-1e6a6480-0236-11ea-860b-1023cf19e8d9.png)

A narrower sweep suggests the effect is not super narrow.

Owen

**Comment by owenduffy** [comment]
![nanovnah05](https://user-images.githubusercontent.com/4297310/68456486-fab51780-0251-11ea-9458-77011b81d33c.jpg)

I have checked the shield... it is different to pics I have seen of other / earlier PCBs. This has a couple of spring clips along the sides of the shield, and an internal edge of the Port 1 shield. I removed the shield, no change. I touched various chips and it makes no significant change. If it is leakage, it does not seem to be field coupled, but rather conducted.
I went over the back of the board with a loupe and it is clean, and the soldering is good to excellent.

I raised this issue to be sure that there was not some firmware processing that might change something around 7.5MHz, or that might create 7.5MHz clock or data sigs to 'peripherals'.

Owen

**Comment by qrp73** [comment]
By the way, the glitch you're talking about is just 0.05 dB. It is just zoomed on your screen.

0.05 dB is pretty good for hardware.

I have NanoVNA-H hardware and it also has some spike a little below 7 MHz. So it seems like some PCB resonance.

![glitch-7MHz](https://user-images.githubusercontent.com/46676744/68470692-3d142f80-0225-11ea-9264-02c31079fc74.png)

**Comment by qrp73** [comment]
you can ask @hugen79 about this spike. I'm not sure about your pcb, because it has blue color. Original hugen79 pcb has green color. But I don't know about v3.3. Just ask @hugen79, may be he can help to reduce it. But anyway it looks acceptable.

**Comment by qrp73** [comment]
I think this is some hardware design issue. But to make sure, clean it with alcohol. Even if looks clean it may contains flux after soldering which affects RF performance.

And try to measure it with removed shield, does it change something?

**Comment by owenduffy** [comment]
> 
> 
> you can ask @hugen79 about this spike. I'm not sure about your pcb, because it has blue color. Original hugen79 pcb has green color. But I don't know about v3.3. Just ask @hugen79, may be he can help to reduce it. But anyway it looks acceptable.

The glitch is small, but it becomes more evident in transformation to Z.

![Screenshot-191108053544](https://user-images.githubusercontent.com/4297310/68488577-76868280-0299-11ea-8ec5-48a3a7177e83.png)

The glitch seem clearest on the blue trace is consistent and much larger than the random measurement noise.

If there is nothing in your firmware that would cause this, then I agree it would seem to be a hardware design issue.

The artifact disappears if the sweep range is EXACTLY the same as the cal range, as the underlying instrument error appears in both data sets and is fully compensated in the corrected trace, but if the cal data set is interpolated, the correction is not complete.

Owen

**Comment by owenduffy** [comment]
I have been over the board with a small sniffer loop on Port 1 (CH1 in nanovna speak) looking for emission peaks around 7.5MHz. I used this method as I understand some activity is ceased during measurement capture, so this measurement is synchronised with that. I could find 30dB hot spots, but nothing with a clear peak around 7.5MHz.

Owen

**Comment by qrp73** [comment]
if you can see this spike with reset calibration, then it is caused by some hardware issue. It looks like some parasitic resonance, most of all some issue with PCB layout.

**Comment by qrp73** [comment]
I suggest you to clean PCB with alcohol, because thin film of flux which remains after soldering may leads to the same issues.

**Comment by qrp73** [comment]
PCB mask also may leads to such issues, some polymers used for PCB mask has bad properties on RF frequencies. This is why critical parts of RF transmission line for measurement device didn't covered with mask. It's hard to predict PCB mask influence. Since your PCB has blue mask, it is definitely consist different polymer than original green PCB from hugen79, so this blue mask material may cause such effect...

**Comment by qrp73** [comment]
Can you show device screenshot for 10kHz - 1500 MHz sweep taken with RESET calibration?

Here is mine (hardware v3.1 from hugen79):

Open CH0 and CH1:
![reset-cal](https://user-images.githubusercontent.com/46676744/68520454-92415700-02a0-11ea-9fd3-995550640230.png)

50 Ohm load on both CH0 and CH1:
![reset-cal-load](https://user-images.githubusercontent.com/46676744/68520538-31664e80-02a1-11ea-9796-a8331cc10290.png)

**Comment by owenduffy** [comment]
I washed the board with alcohol and dried it. No change.

A 101 point scan from 10k to 1500M will not expose the spike at 7.5MHz, the scan skips over it.

I discovered this following up a persistent glitch in a choke measurement across HF, and it appears the glitch is inherent to the hardware.

**Comment by qrp73** [comment]
> A 101 point scan from 10k to 1500M will not expose the spike at 7.5MHz, the scan skips over it.

yes, but it exposes overall performance of hardware RF frontend and shows what you can expect from it. If it shows bad overall performance, there is no sense to expect good performance at narrow band.

**Comment by owenduffy** [comment]
In looking at the schematic for -H v3.3.1, I note the mixers use a decoupling filter of a 4.7µH choke and 100pF cap, and the self resonant freq is 7.35MHz. I wonder if other boards of this design exhibit this small peak.

The NXP datasheet shows a much lower break point filter.

![Screenshot-191109172414](https://user-images.githubusercontent.com/4297310/68524049-dd498180-0315-11ea-835b-cfd428fb48cd.png)

I note the 'improved' -H circuit is different to the original edy cct. Presumably this was to fix some problem. I have ordered some 100nF caps to piggyback onto the 100pF on pin 8, due for delivery by 18/11.

**Comment by owenduffy** [comment]
The caps arrived more quickly than I expected.

I have piggybacked 100nF on C40, C42, C44 on a nanovna-H v3.3 PCB.

![Screenshot-191112112546](https://user-images.githubusercontent.com/4297310/68631519-3811f180-053f-11ea-9b1f-0d63e1c81af3.png)

The artifacts evident in the earlier 6.6-8.5MHz R,X sweep are gone.

Problem fixed, the glitch identified was caused by a lack of bypassing of the Vcc pin of the three SA612AD mixers, the installed capacitor was resonating with the series choke to fairly ruin decoupling around 7.5MHz.

This hardware defect is probably in all nanovna-H PCB up to and including v3.3.

Owen

**Comment by hugen79** [comment]
> The caps arrived more quickly than I expected.
> 
> I have piggybacked 100nF on C40, C42, C44 on a nanovna-H v3.3 PCB.
> 
> ![Screenshot-191112112546](https://user-images.githubusercontent.com/4297310/68631519-3811f180-053f-11ea-9b1f-0d63e1c81af3.png)
> 
> The artifacts evident in the earlier 6.6-8.5MHz R,X sweep are gone.
> 
> Problem fixed, the glitch identified was caused by a lack of bypassing of the Vcc pin of the three SA612AD mixers, the installed capacitor was resonating with the series choke to fairly ruin decoupling around 7.5MHz.
> 
> This hardware defect is probably in all nanovna-H PCB up to and including v3.3, possibly also in the upcoming v3.4.
> 
> Owen

I will improve this issue in NanoVNA-H  V3.4.

hugen

**Comment by owenduffy** [comment]
Ok, noted. I amended blog write up:

"This hardware defect is probably in all nanovna-H PCB up to and including v3.3. Hugen79 tells me he intends fixing this in the upcoming v3.4."

Some more discussion and pics at https://owenduffy.net/blog/?p=16058 .
