### ISSUE TITLE
Averaging does not seem to work as I expect v0.4.4

### ISSUE THREAD

**Issue by owenduffy** [qrp73/NanoVNA-Q#17]
I have done some raw scans of a short from 1-10MHz to visually asses the reduction in measurement noise.

Without averaging:

![Screenshot-191127070200](https://user-images.githubusercontent.com/4297310/69668493-29e9d680-10e4-11ea-8e98-448dffbc1a50.png)

With average on:

![Screenshot-191127070124](https://user-images.githubusercontent.com/4297310/69668545-4ab22c00-10e4-11ea-9b83-be2ce7a75729.png)

There seems higher standard deviation with average on.

I have taken these plots with nanovnasharp, "nanovna MOD v3" chokes on the longer sweep times.

I expected there should be a reduction in standard deviation of sqrt(n). What is averaging n?

Owen

**Comment by owenduffy** [comment]
Another interesting observation is of phase.

This is phase with a open, and there is an apparent 'modulation' with freq or time.
![Screenshot-191128153250](https://user-images.githubusercontent.com/4297310/69777466-889e7580-11f4-11ea-8782-f781cab0c8da.png)

Whereas the un-averaged jitter looks like:

![Screenshot-191128153502](https://user-images.githubusercontent.com/4297310/69777503-af5cac00-11f4-11ea-916e-badb5335fcb2.png)

I expected to see random jitter in the first plot, and of about a third the jitter amplitude of the second plot.

Owen

**Comment by qrp73** [comment]
This is interesting. I will check it.
Did you performed calibration in average mode for these measurements? 

> What is averaging n?

averaging N = 10

**Comment by owenduffy** [comment]
These are all raw scans of s11, ie "uncorrected".

We might expect the the standard deviation of measurements averaged over N observations is reduced by SQRT(N), so N=10 gives 1/3.16, N=16 gives 1/4 etc.

Owen

**Comment by d51r3verse** [comment]
> We might expect the the standard deviation of measurements averaged over N observations is reduced by SQRT(N), so N=10 gives 1/3.16, N=16 gives 1/4 etc.

Implented similar std deviation for S21 jitter( /w 30 samples for calibration ).
I used Python and using `N-1` instead of `N`
No luck to smoothing

**Comment by owenduffy** [comment]
I did battle with nanovna-saver to try to use it to average a raw sweep. Its plots are not well labelled, but it seems this is |s11|, raw with no averaging.
![Screenshot-191129113124](https://user-images.githubusercontent.com/4297310/69836332-3b75de80-129c-11ea-8c34-98ef1a8aa60c.png)
The Y scale needs some interpretation,... and this is with nanovna-saver  averaging, N=16:
![Screenshot-191129113041](https://user-images.githubusercontent.com/4297310/69836347-4c265480-129c-11ea-989f-65947b1d7388.png)
One can see the jitter has been reduced significantly, and we might expect to a quarter.
We should hope for similar effect with -Q's internal average facility.

Owen

**Comment by owenduffy** [comment]
> 
> 
> > We might expect the the standard deviation of measurements averaged over N observations is reduced by SQRT(N), so N=10 gives 1/3.16, N=16 gives 1/4 etc.
> 
> Implented similar std deviation for S21 jitter( /w 30 samples for calibration ).
> I used Python and using `N-1` instead of `N`

Speaking to N-1:

The sum of several random variables results in a random variable with Mean equal to the sum of the Means and Variance equal to the sum of the Variances.

If we assume that on averaging, each of n samples a random variable drawn from the population with some Mean and Standard Deviation, we would expect the Mean of the Means to be the Mean of the population, and the expected Variance to be n times the expected Variance of one sample, and so the expected Standard Deviation of n samples would be the expected Standard Deviation of one sample divided by square root of n.

Here is a summary of an experiment measuring an open on the nanovna uncorrected.

![Clip 081](https://user-images.githubusercontent.com/4297310/69890706-4b98c700-134b-11ea-93c6-41e64e174538.png)

Effectively each measurement is based on 101 scan points from 10.0000MHz to 10.0001MHz, as good as 100 samples of the noise in each measurement, and the SD calculated from the sample.

The expected value plotted is based on the first measurement divided by N^2.

Obviously, the square law behaviour runs out at some point as things like temporal stability affect the results. My AIMuhf is an analyser that fails on large averages because of thermal drift in the chipset.

Owen
