### ISSUE TITLE
Incompatibility -Q & nanovna MOD v3

### ISSUE THREAD

**Issue by owenduffy** [qrp73/NanoVNA-Q#19]
nanovna MOD v3 and -Q v0.4.4 have an incompatibility if -Q average is turned on.
If I click "get data" it often fails to complete and disconnects.

I can trick it to work reliably by waiting about 2s after a screen update on the nanovna and then hitting "get data".

It seems as though nanovna MOD v3 may not get a timely response when the nanovna-Q is 'working'. Either -Q is not responding as quickly as it should, or nanovna MOD v3 does not wait as long as it needs to.

Owen

**Comment by qrp73** [comment]
thanks, I can reproduce it, will be fixed in future release
