### ISSUE TITLE
Initial pointer to recall 0 missing after flashing 0.4.4

### ISSUE THREAD

**Issue by nlroth** [qrp73/NanoVNA-Q#21]
Although when the Nano is power cycled it will automatically recall memory 0, if you try to manually recall 0 after startup, nothing happens.  This is only after flashing 0.4.4 to the unit. 

However, if you turn on the Nano and immediately save to memory 0, it will now recall 0 manually. 

Probably a pointer missing somewhere. Not a big issue. Only happens after initial flash of 0.4.4

**Comment by qrp73** [comment]
it recalls memory 0. But it is not compatible with memory content from other firmware (include NanoVNA-Q old version). So, if memory 0 has incompatible values, it ignore it and loads default values.

Just save memory 0 and after power off it will be restored.

**Comment by nlroth** [comment]
Yes, that is what I did.
Thanks

    On Monday, December 23, 2019, 4:18:57 p.m. GMT-5, qrp73 <notifications@github.com> wrote:  
 
 
it recalls memory 0. But it is not compatible with memory content from other firmware (include NanoVNA-Q old version). So, if memory 0 has incompatible values, it ignore it and loads default values.

Just save memory 0 and after power off it will be restored.
